config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'users#new'
  match 'users/create' => 'users#create', via: [:get, :post] 
  match 'refer-a-friend' => 'users#refer', via: [:get, :post]
  get '/admin' => 'users#admin'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :referrer, class_name: "User", foreign_key: "referrer_id"
  has_many :referrals, class_name: "User", foreign_key: "referrer_id"

  validates :email, uniqueness: true
  validates :referral_code, uniqueness: true

  before_create :create_referral_code

  REFERRAL_STEPS = [
    {
        'count' => 5,
        "html" => "Coffee<br>Mug",
        "class" => "two",
        "image" =>  ActionController::Base.helpers.asset_path("refer/cream-tooltip@2x.png")
    },
    {
        'count' => 10,
        "html" => "Pizza",
        "class" => "three",
        "image" => ActionController::Base.helpers.asset_path("refer/truman@2x.png")
    },
    {
        'count' => 25,
        "html" => "Lunch with Walter",
        "class" => "four",
        "image" => ActionController::Base.helpers.asset_path("refer/winston@2x.png")
    },
    {
        'count' => 50,
        "html" => "Free<br>Wyncode",
        "class" => "five",
        "image" => ActionController::Base.helpers.asset_path("refer/blade-explain@2x.png")
    }
  ]

  def admin?
    self.role == 'admin'
  end

  private

    def create_referral_code
  	  #generate random hexadecimal referral code
      referral_code = SecureRandom.hex(5) 
      #find other user with the same referral code, if any
      @collision = User.find_by_referral_code(referral_code)
      #while other users with the same referral code are found
      while !@collision.nil?
    	#re-generate the referral code
    	  referral_code = SecureRandom.hex(5)
      end
      #unique referral code generated; save to current user
      self.referral_code = referral_code
    end

      ## Send email to registered user 
    def send_welcome_email
        UserMailer.signup_email(self) #removed .delay
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ref_to_cookies

  protected
  #method to save query string (?ref=) in cookies hash
  def ref_to_cookies
  	#if query string exists
  	if params[:ref]
  	  #if a User with the same referral code as in query string value found
      if !User.find_by_referral_code(params[:ref]).nil?
      	#save the value of the query string in the cookies hash
        cookies[:h_ref] = {value: params[:ref]}
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #only before new action, call skip_to_refer
  before_action :skip_to_refer, :only => :new
  
  #authenticate admin user before accessing admin action
  before_action :authenticate_admin!, :only => :admin
  
  def new
		@user = User.new
	end

	def create
		#find a User with the same email
		@user = User.find_by_email(:email)

		#if User does not exist
		if @user.nil?
			#create a new instance of User with email
			@user = User.new(user_params)
		
			#get the User with the same referral code as in the cookies hash
			@referred_by = User.find_by_referral_code(cookies[:h_ref])

			#if User found, set current User's referrer
			if !@referred_by.nil?
				@user.referrer = @referred_by
			end

			#save instance of current user
			@user.save

			# Sends email to user when user is created
      		UserMailer.signup_email(@user).deliver_now

			#delete referral code in cookies hash
			cookies.delete :h_ref

	  end
		#save current User's email in cookies hash for access in refer action
		cookies[:h_email] = {value: @user.email}
			
		#redirect to refer action (i.e. main referrable page)
		redirect_to '/refer-a-friend'			
	end

	def refer
		#retreive the current User's email from the cookies hash
		email = cookies[:h_email]

		#retreive current User
		@user = User.find_by_email(email)

		#if User not found
		if @user.nil?
			redirect_to root_path
		end
	end

	def skip_to_refer
		email = cookies[:h_email]
		if email and !User.find_by_email(email).nil?
		  redirect_to '/refer-a-friend'
		else
		  cookies.delete :h_email
		end 
	end

	def admin
		  #allow admin acess to all users
      @users = User.all

      #needed for testing
      cookies.delete :h_email
	end

	private
	def user_params
		params.require(:user).permit(:email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Referable</title>
  	<link rel="stylesheet" href="https://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Domine' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:300italic,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
     	<%= image_tag("referable-logo.png", alt: "Signup") %>
  </div>
</div>

<%= yield %>

<div class="footer">
  <div class="container">
      <p>® Copyright 2015</p>
  </div>
</div>

</body>
</html>

app/views/users/admin.html.erb
<div class="leaderboard">
  <div class="container">
        <h1>Referrable Leaderboard</h1>
          <table class="table table-striped table-bordered table-condensed">
            <tbody>
              <tr>
               <th>User</th>
               <th>Referrals</th>
              </tr>
              <% @users.sort_by{|u| u.referrals.count }.reverse.each do |u| %>
            <tr>
              <td><%= u.email %></td>
              <td><%= u.referrals.count %></td>
            </tr>
              <% end %>
            </tbody>
          </table>
          <%= button_to "Logout", destroy_admin_session_path,method: :delete, :class =>"primary-btn" %>
  </div>
</div>

app/views/users/leaders.html.erb
<div class="leaderboard">
  <div class="container">
        <h1>Referrable Leaderboard</h1>
          <table class="table table-striped table-bordered table-condensed">
            <tbody>
              <tr>
               <th>User</th>
               <th>Referrals</th>
              </tr>
              <% @users.sort_by{|u| u.referrals.count }.reverse.each do |u| %>
            <tr>
              <td><%= u.email %></td>
              <td><%= u.referrals.count %></td>
            </tr>
              <% end %>
            </tbody>
          </table>
          <%= button_to "Back to Referable", refer_a_friend_path, :method => "get", :class =>"primary-btn" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<h1>Make The Products You Love Referable</h1>
				<p>Be the first to learn when this product launches.</p>
				  <%= form_for @user, url: {action: "create"} do |f| %>
					<%= f.label :email %>
					<%= f.email_field :email, :class => "form", :placeholder => "your@email.com"%>
					<%= f.submit "Spread the word!", :class => "primary-btn"%>
				  <% end %>
			</div>
		</div>
		<div class="row supporting">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="box">
					<%= image_tag("heart.png", alt: "Signup") %>
					<h2>Signup</h2>
					<p>Be the first to know when we officially launch.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12 ">
				<div class="box">
					<%= image_tag("paperplane.png", alt: "Refer") %>
					<h2>Refer</h2>
					<p>Share products you love with your network of friends.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="box">
					<%= image_tag("banknote.png", alt: "Earn") %>
					<h2>Earn</h2>
					<p>Get rewarded for turning your friends into customers.</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/refer.html.erb
  <%
    referrals_count = @user.referrals.count

    stops = User::REFERRAL_STEPS
  
    found = nil

    next_stop = nil

    stops.reverse_each { |stop|
        if stop["count"] <= referrals_count and !found
            stop["selected"] = true
            found = stop
            current_index = stops.index(stop)
             next_stop = stops.at(current_index + 1)
        else
            stop["selected"] = false
            next_stop = stops.at(0)
        end
    }
  %>


<div class="summary">
  <div class="container">
    <div class="row content">
      <div class="col-md-6 col-sm-12 col-xs-12 thanks">
        <h1>Thanks For Signing Up!</h1>
        <h4>Spread the word by sharing this link with your friends</h4>
        <div class="ref-link"><%= root_url %>?ref=<%= @user.referral_code %></div>
        <div class="box">
          <a href="mailto:?subject=Check out the Referable App&body=Hi,%0D%0A%0D%0A I found this awesome app and thought you might like it:%0D%0A%0D%0A https://referable.herokuapp.com/?ref=<%= @user.referral_code %> %0D%0A%0D%0A I hope you like it!">
          <div class="primary-btn">Share</div>
          </a>
        </div>
      </div>
      <div class="col-md-6 col-sm-12 col-xs-12 refer">
        <div class="box">
          <h2>Referral Summary</h2>
          <% referrals_count = @user.referrals.count %>
          <% if referrals_count == 0 %>
            <p><span>No</span> friends have joined...Yet!</p>
          <% else %>
            <p>Total referrals: <strong><%= referrals_count %></strong> have joined!</p>
              <% if referrals_count >= 5 && referrals_count < 10 %>
                <p>You Won One Free Pizza!</p>
              <% elsif referrals_count >= 10 && referrals_count < 25 %>
                <p>You Won 3 Months of Free Ramen!</p>
              <% elsif referrals_count >= 25 && referrals_count < 50 %>
                <p>You Won 6 Months of Free Coffee!</p>
              <% elsif referrals_count >= 50 %>
                <p>Holy Cow, You Won 1 Year of Free Beer!</p>
              <% else %>
                <p></p>
              <% end %>
          <% end %>
          <% if referrals_count >= 50 %>
            <p>You Got The Biggest Reward! Thank you for your support!</p>
            <% else %>
            <p>You are <strong><%= next_stop["count"]-referrals_count%></strong> referrals away from unlocking your next reward!</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="rewards">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="box">
          <%= image_tag("pizza.jpg", alt: "Earn") %>
          <p>One Whole Pizza!</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="box">
          <%= image_tag("ramen.jpg", alt: "Earn") %>
          <p>3 Months of Ramen!</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="box">
          <%= image_tag("coffee.jpg", alt: "Earn") %>
          <p>6 Months of Coffee!</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="box">
          <%= image_tag("beer.jpg", alt: "Earn") %>
          <p>1 Year of Beer!</p>
        </div>
      </div>
    </div>
  </div>
</div>